### ISSUE TITLE
Square Icon

### ISSUE THREAD

**Issue by Jogai** [dcurtis/markdown-mark#14]
Works better for desktop icons / favicons.

Here is one i'm using now: http://cargocollective.com/inami/Markdown

**Comment by Krinkle** [comment]
> Here is one i'm using now: http://cargocollective.com/inami/Markdown

Captured here for posterity.
![markdown_860](https://cloud.githubusercontent.com/assets/156867/9456414/82d98236-4ad7-11e5-871b-002a30128cee.png)
