### ISSUE TITLE
Use different arrow in Unicode approximation

### ISSUE THREAD

**Issue by waldyrious** [dcurtis/markdown-mark#17]
The current arrow doesn't look like the one in the mark, since the head is made of two lines rather than a triangle. A better approximation could be ⬇ (downwards black arrow, U+2B07) or ⭣ (downwards triangle-headed arrow, U+2B63). The former seems to have better font support.

**Comment by jeffmcneill** [comment]
I can't see the U+2B63 icon for some reason. 

![screen shot 2015-08-27 at 11 52 53](https://cloud.githubusercontent.com/assets/3119827/9512863/47520abc-4cb2-11e5-9995-809d293e4d2d.png)

The U+2B07 looks great. Prefaced with an **M**⬇ is perfect.

**Comment by waldyrious** [comment]
Yup, in my system it doesn't look right either. Apparently [only 3 fonts support it at the moment](http://www.fileformat.info/info/unicode/char/2b63/fontsupport.htm): GNU Unifont, PragmataPro and Symbola. [This page](http://unicode-table.com/en/2B63/) shows it as text, but I suppose they're embedding a webfont to achieve that.

**Comment by waldyrious** [comment]
For future reference: the change proposed above (from `M↓` to `M⬇`) was applied in commit ad1e60642.
