### ISSUE TITLE
Font of the "M"

### ISSUE THREAD

**Issue by vimtaai** [dcurtis/markdown-mark#19]
Hi!
Can you tell what font was used for the "M" in the Markdown Mark? Or is it drawn from scratch? It would be nice to be able to add letters to the mark while maintaining style consistency.
Thanks

**Comment by dcurtis** [comment]
It is a customized version of the capital M glyph in Gill Sans Bold.

**Comment by vimtaai** [comment]
Thanks for the response. I also found Gill Sans Bold to be the closest match of what I could find so thanks for confirming it. :)
