### ISSUE TITLE
Extension won't download file if reserved character is in title

### ISSUE THREAD

**Issue by orangepillpixel** [dcurtis/markdown-mark#25]
I was trying to download this page as markdown 

https://gearspace.com/board/electronic-music-instruments-and-electronic-music-production/197168-tips-making-ambient-drones-steve-roach-drone-zone-style.html

but the download wouldn't work as there was a slash (/) in the title - I finally worked out how to correct this by editing the title but could we look at substituting reserved characters automatically?

i.e https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

**Comment by dcurtis** [comment]
This is not relevant to this repository.
