### ISSUE TITLE
Not proper link assigned 

### ISSUE THREAD

**Issue by kuchaale** [dcurtis/markdown-mark#31]
"Copy Tab URL as Markdown Link" does not copy properly links from [this website](https://egusphere.copernicus.org/preprints/2024/egusphere-2024-1428/) for instance. It does not include the link, see `[EGUsphere - Warming effects of reduced sulfur emissions from shipping](moz-extension://d7e0be0e-a147-47b5-8d24-d65e7920a6b6/)`. Otherwise, awesome work!

**Comment by dcurtis** [comment]
This report not relevant to this project.

**Comment by kuchaale** [comment]
I am sorry for the misplaced issue :)
